platform :ios, '7.0'
pod 'AFNetworking'
pod 'Mantle'
pod 'LBBlurredImage'
pod 'HexColors'
pod 'TSMessages'
pod 'ReactiveCocoa'
pod 'Facebook-iOS-SDK'
pod 'IOSLinkedInAPI'
pod 'Foursquare-iOS-API'
pod 'Foursquare-API-v2'
pod 'unoffical-twitter-sdk'
pod 'FlickrKit'
pod 'google-plus-ios-sdk'
#pod 'gtm-oauth2'
#pod 'gtm-http-fetcher'
#pod 'Google-API-Client'
#pod 'XNGAPIClient'
#pod 'iOS-GTLYouTube'
pod 'Dropbox-iOS-SDK'
pod 'Pinterest-iOS'
pod 'InstagramKit'
pod 'TMTumblrSDK'
pod 'MBProgressHUD'
pod 'BiergartenFetcher', :path => '/Users/platzerworld/Specs/BiergartenFetcher/0.0.1'